{% set name = "act" %}
{% set version = "0.2.74" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nektos/act/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 589e4d5f58ee180963f16ecbc083b7c1af58642a6704c49c38ce5fda95800105

build:
  number: 0

  script:

    - export GOFLAGS="'-ldflags=-X main.version={{ version }}'"  # [unix]
    - set GOFLAGS='-ldflags=-X main.version={{ version }} '       # [win]

    - unset CONDA_GO_COMPILER;  # [not win]
    - go build -o act main.go
    - mkdir $PREFIX/bin && cp act $PREFIX/bin/act  # [not win]
    - dir && mkdir %PREFIX%/bin && copy act %PREFIX%/bin/act  # [win]
    # TODO: This is due to a bug in our go-lang patch
    #       Error message is go install can't write to GOBIN when cross compiling
    - go-licenses save . --save_path "./license-files/"

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses



test:
  commands:
    - act --version

about:
  home: https://nektosact.com
  summary: 'Run your GitHub Actions locally!'
  description: |
    Run your GitHub Actions locally! Why would you want to do this? Two reasons:
    - Fast Feedback - Rather than having to commit/push every time you want to test out
      the changes you are making to your .github/workflows/ files (or for any changes to
      embedded GitHub actions), you can use act to run the actions locally. The environment
      variables and filesystem are all configured to match what GitHub provides.
    - Local Task Runner - I love make. However, I also hate repeating myself. With act, you
      can use the GitHub Actions defined in your .github/workflows/ to replace your Makefile!
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - license-files/
  doc_url: https://nektosact.com
  dev_url: https://github.com/nektos/act

extra:
  recipe-maintainers:
    - zklaus
    - hobu
