{% set name = "act" %}
{% set version = "0.2.76" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nektos/act/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0cc577eba16c75016fc5a61f8d91a358cb9b470b601f5e14f0e94948101a31df

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses



test:
  commands:
    - act --version

about:
  home: https://nektosact.com
  summary: 'Run your GitHub Actions locally!'
  description: |
    Run your GitHub Actions locally! Why would you want to do this? Two reasons:
    - Fast Feedback - Rather than having to commit/push every time you want to test out
      the changes you are making to your .github/workflows/ files (or for any changes to
      embedded GitHub actions), you can use act to run the actions locally. The environment
      variables and filesystem are all configured to match what GitHub provides.
    - Local Task Runner - I love make. However, I also hate repeating myself. With act, you
      can use the GitHub Actions defined in your .github/workflows/ to replace your Makefile!
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - license-files/
  doc_url: https://nektosact.com
  dev_url: https://github.com/nektos/act

extra:
  recipe-maintainers:
    - zklaus
    - hobu
